### ISSUE TITLE
Fix snapshot publishing

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s-jdk-http-client#147]
```
Run echo $PGP_SECRET | base64 --decode | gpg --import
base64: invalid input
```

I exported a key and base64 encoded it, but apparently not in the format necessary to create something that works with that command.  Does anybody remember the correct incantation?

**Comment by amesgen** [comment]
It is indeed very confusing that the base64 decoding seems to fail.

Hmm, is PGP_SECRET bigger than 64KB ([see here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#limits-for-secrets))? For my key,
```
$ gpg --export-secret-keys 0BC58F292D5F87E12AADD2BF1A89EC203635A13D | base64 | wc -c
```
results in ~12KB.


```
export PGP_SECRET=$(gpg --export-secret-keys 0BC58F292D5F87E12AADD2BF1A89EC203635A13D | base64)
echo $PGP_SECRET | base64 --decode | gpg --import
```
works fine for me.

**Comment by amesgen** [comment]
Maybe using `base64 -w 0` is needed to prevent the newlines in the output? Pasting multi-line text in the github secrets web interface might be the problem.

**Comment by rossabaker** [comment]
I think the `-w 0` might be it.  Updating the secret and trying again.

**Comment by amesgen** [comment]
Sadly not fixed, will look into it later https://github.com/http4s/http4s-jdk-http-client/runs/421132877#step:6:25

**Comment by rossabaker** [comment]
I think #155 will fix that, but I don't know what lurks beyond that.

**Comment by amesgen** [comment]
Ok, the private key appears to have the same base64 issue. [src](https://github.com/http4s/http4s-jdk-http-client/runs/421152933?check_suite_focus=true#step:6:26)

**Comment by rossabaker** [comment]
Two problems fixed: 
* the ssh key isn't base64 encoded (#156)
* when we echo a variable with new lines unquoted, the shell splits those into arguments (b8961df5ef2b4fe84cee7e5c9effcd70dbcd8efb)

Back to ioctl woes.

**Comment by rossabaker** [comment]
Success with c48df4c3e9280f18673d8760ed313c0b724b775f, found in [scalatyle](https://github.com/beautiful-scala/scalastyle/blob/b1588975f9ac05f59b3c07139b62b0f9bb904e28/.github/workflows/release.yml#L18-L23).

Sorry for the master pushes, but this is fiddly work.  Now back to regular PRs and real code. :smile:
