### ISSUE TITLE
Fs2 > 2.4.5 Binary Compatibility Issue

### ISSUE THREAD

**Issue by isomarcte** [http4s/http4s-jdk-http-client#321]
Using this project with a transitive dependency on fs2 >= 2.4.5 (current release uses 2.4.2) will create a runtime failure. This isn't an issue with the jdk client directly, but I thought it would be good to raise awareness here.

https://github.com/typelevel/fs2/issues/2177

On the one hand, cutting a new release against 2.4.6 of fs2 would solve this issue, but on the other depending on what fs2 decides to do that might break again.

**Comment by amesgen** [comment]
If we cut a new release, it will stop working with fs2 < 2.4.6, or do I misunderstand something?

**Comment by isomarcte** [comment]
> If we cut a new release, it will stop working with fs2 < 2.4.6, or do I misunderstand something?

A release built against 2.4.5 or later won't work with 2.4.4 or older. 

There doesn't appear to be a great solution here, cutting a release breaks some clients, not cutting one breaks other.

**Comment by isomarcte** [comment]
@amesgen Oh I didn't see that you already cut a release. :+1:

**Comment by amesgen** [comment]
0.3.2 hould now be in [Maven Central](https://search.maven.org/search?q=http4s-jdk-http-client).

**Comment by isomarcte** [comment]
@amesgen thanks!

**Comment by rossabaker** [comment]
A release cut against 2.4.5 should evict 2.4.4 in apps. The problem is other dependencies compiled for 2.4.4 that depend on the missing signature. Everyone (e.g., http4s-core) should probably release a patch.
