### ISSUE TITLE
"java.io.IOException: HTTP/1.1 header parser received no bytes" over HTTPS Proxy

### ISSUE THREAD

**Issue by sushengloong** [http4s/http4s-jdk-http-client#494]
Hi, I encounter `java.io.IOException: HTTP/1.1 header parser received no bytes` when making an API call through an authenticated HTTPS proxy. 

This is how I instantiated the client.
```
Resource
        .eval(F.delay {
          val proxyHost = config.proxyHost
          val proxyPort = 8443
          HttpClient
            .newBuilder()
            .version(HttpClient.Version.HTTP_1_1)
            .sslContext(buildSSLContext())
            .proxy(ProxySelector.of(new InetSocketAddress(proxyHost, proxyPort)))
            .build()
        })
        .flatMap(JdkHttpClient(_))

private def buildSSLContext(): SSLContext = {
    val keyStore = KeyStore.getInstance(KeyStore.getDefaultType())
    keyStore.load(null)

    val certFileStream = this.getClass.getResourceAsStream("/path/to/cert.pem")
    val certificate    = CertificateFactory.getInstance("X.509").generateCertificate(certFileStream)
    keyStore.setCertificateEntry("cert", certificate);

    val tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm())
    tmf.init(keyStore)
    val trustManagers = tmf.getTrustManagers()

    val sslContext = SSLContext.getInstance("TLS")
    sslContext.init(null, trustManagers, null)
    sslContext
  }
```

I have also tried removing TLS1.3 by following the [this approach](https://github.com/http4s/http4s-jdk-http-client/blob/6231460b7f4d3ecaf4a01424aeed5e39b491cd72/core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala#L259-L263) but to no avail.

This is largely how I set the header and make the API call
```
Uri.fromString(url).liftTo[F].flatMap { uri =>
            val reqEntity =
                    MyRequest(
                        ... (omitted)
                    )

            val requestHeaders = {
                    val proxyCredentials = BasicCredentials(
                        config.proxyUsername,
                        config.proxyPassword
                    )
                    Headers(
                        Header.Raw(ci"Proxy-Authorization", s"Basic ${proxyCredentials.token}"),
                        Header.Raw(ci"X-API-key", config.apiKey),
                    )
                }

            val request = Request[F](
                method = Method.POST,
                uri = uri,
                headers = requestHeaders
            )
            .withEntity(reqEntity)

            client.run(request).use { response =>
                ...
            }
            .recoverWith {
                case e =>
                    for {
                        _ <- Logger[F].error(s"Error when calling API: $e: ${e.getMessage}") // the exception is logged here
                        err <- Exception.APICallError.raise[F, MyResponse] // throw my custom exception
                    } yield err
            }
        }
```

Any help would be appreciated!

**Comment by amesgen** [comment]
Can you try to reproduce the issue without http4s-jdk-http-client, but only with [`java.net.http.HttpClient`](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html)?

**Comment by sushengloong** [comment]
Hi @amesgen, thank you for your response. I was able to reproduce the issue with only `java.net.http.HttpClient`. Do you have any advice?

**Comment by amesgen** [comment]
- Trying to reproduce the issue with another HTTP client (e.g. via another http4s backend with proxy support).
 - Maybe the proxy is misbehaving?
 - An universal reason for these kinds of things could be random network failures.

Either way, for now, it does not seem that this issue is related to http4s-jdk-http-client, so I am closing it. But feel free to post an update here if you find a solution!

**Comment by sushengloong** [comment]
It turns out that the proxy service we use is not functional on port 8443 (miscommunication by the proxy service owner). Everything is good with http4s-jdk-http-client and `java.net.http.HttpClient`. Thank you so much!

**Comment by amesgen** [comment]
Great to hear, glad you found the issue!
