### ISSUE TITLE
When is a new version going to be released?

### ISSUE THREAD

**Issue by andreisilviudragnea** [http4s/http4s-jdk-http-client#513]
We need a newer version of `fs2-core` in our project and the older incompatible version is brought by `http4s-jdk-http-client`.

**Comment by andreisilviudragnea** [comment]
Yes, of couse. I just thought this is a problem that should not happen. I think this dependency configuration would still fail by sbt's [eviction warnings](https://www.scala-sbt.org/1.x/docs/Library-Management.html#Eviction+warning) rules.

**Comment by amesgen** [comment]
So this is resolved?

---

Small nitpick:

> `fs2-core:3.0.6` and `fs2-core:3.1.2` are binary incompatible. For example, there is no `f2s.text.uft8` class in `fs2-core:3.0.6`.

Usually, a version W is called "binary compatible" to another version V of a package P if a library L, which was compiled against version V of package P, will continue to work when version W is supplied on the classpath. In particular, this means that API additions often do not break binary compatiblity.
