### ISSUE TITLE
Implement WebSocket Client API from http4s-client

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-jdk-http-client#568]
It should be straightforward to implement, since the model/API was heavily based on the one currently the jdk-http-client.

@amesgen do you have any strategy in mind wrt compatibility?

**Comment by amesgen** [comment]
Currently, we have three active branches:

 - 0.4 for http4s 0.22
 - 0.5 for http4s 0.23
 - 0.6 (currently snapshots) for http4s 1.0

My initial reaction would be to now start using this branch setup instead:

 - 0.7 for http4s 0.22 with the WS client model in http4s-client
 - 0.8 for http4s 0.23 with the WS client model in http4s-client
 - 1.0 (snapshots) for http4s 1.0 (we are still in the snapshot territory, so we can break binary compatibility when a WS model lands)

WDYT?

**Comment by armanbilge** [comment]
👍 for the proposed versioning scheme. I guess there's no nice way to implement the new model while keeping compatibility with the old, but that's fine.

**Comment by rossabaker** [comment]
It's weird for 0.6 -> 0.7 to be a massive rollback in core dependencies, but we're cornered, and anything goes on 0.x.

Alternative: abandon 0.22, and focus on 0.23 (as 0.7?) and 1.0 (as 1.0).

Another alternative: deprecate the existing model, move the new into a `.ws` subpackage (or rename `JdkWsClient`), keep the current versions.

**Comment by armanbilge** [comment]
@amesgen I'd like to work on this if it's okay :) any thoughts about Ross's proposals?

**Comment by amesgen** [comment]
@armanbilge Sure, go ahead, thank you so much for your time! The `series/*` should be up-to-date modulo missing dependency bumps.

> Alternative: abandon 0.22, and focus on 0.23 (as 0.7?) and 1.0 (as 1.0).

This would also be fine by me :+1:

> Another alternative: deprecate the existing model, move the new into a .ws subpackage (or rename JdkWsClient), keep the current versions.

IMO, the new interface is close enough to the old one that going through a deprecation cycle isn't worth it. Also, the WS model in here was always advertised as being subject to change ([src](https://jdk-http-client.http4s.org/latest/index.html#websocket-client)).

**Comment by armanbilge** [comment]
Thanks! 👍 we're dialing down 0.22 in http4s-core anyway, so I'll focus on 0.23 as 0.7.

**Comment by armanbilge** [comment]
Done in https://github.com/http4s/http4s/pull/6001.
