### ISSUE TITLE
Releasing from main as compatible with http4s 1.0.0-M31

### ISSUE THREAD

**Issue by prova** [http4s/http4s-jdk-http-client#580]
Hi,

The current (March 1st 2022) main branch remains unreleased so we have no versions compatible with http4s 1.0.0-M31.

Can the project owners consider releasing from main a new milestone please?

The particular interest we have is support for proxies in the client. To c;confirm, our internal code works well with a custom local version built directly from main.

Cheers

**Comment by amesgen** [comment]
The websocket client interface in http4s-jdk-http-client is package-private, how are you using it? https://github.com/http4s/http4s/blob/v1.0.0-M31/client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala

**Comment by prova** [comment]
> The websocket client interface in http4s-jdk-http-client is package-private, how are you using it? https://github.com/http4s/http4s/blob/v1.0.0-M31/client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala

Not using the WSClient at the moment, only plain Web calls.

**Comment by prova** [comment]
> Oh, which reminds me, there _is_ a snapshot of main available, that is against 1.0.0-M31.
> 
> https://s01.oss.sonatype.org/content/repositories/snapshots/org/http4s/http4s-jdk-http-client_2.13/1.0-10465bf-SNAPSHOT/

That is good, at least we can point to the SNAPSHOT--the one built for Scala 3: https://s01.oss.sonatype.org/content/repositories/snapshots/org/http4s/http4s-jdk-http-client_3/1.0-10465bf-SNAPSHOT/.

Thanks!

**Comment by amesgen** [comment]
> > The websocket client interface in http4s-jdk-http-client is package-private, how are you using it? https://github.com/http4s/http4s/blob/v1.0.0-M31/client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
> 
> Not using the WSClient at the moment, only plain Web calls.

Ah, that makes sense! In that case, I think using snapshots is a good intermediate solution until we release the first milestone from `main` :+1:

**Comment by amesgen** [comment]
[1.0.0-M1](https://github.com/http4s/http4s-jdk-http-client/releases/tag/v1.0.0-M1) just got released, and is compatible with http4s-1.0.0-M32 🎉
